asyncapi: 2.6.0
info:
  title: Product Portfolio
  description: >-
    BIAN Service Domain (expanded with the BIAN BOM) | Maintain a portfolio of
    analytical views of the product portfolio to support product profitability
    and performance analysis
  version: 12.0.3
channels:
  ProductPortfolioAnalysis/Created:
      description: ''
      publish:
        operationId: ProductPortfolioAnalysis-created
        summary: ProductPortfolioAnalysis
        message:
          $ref: '#/components/messages/ProductPortfolioAnalysis'
  ProductPortfolioAnalysis/Updated:
      description: ''
      publish:
        operationId: ProductPortfolioAnalysis-updated
        summary: ProductPortfolioAnalysis
        message:
          $ref: '#/components/messages/ProductPortfolioAnalysis'
  PerformanceAnalysis/Created:
      description: ''
      publish:
        summary: PerformanceAnalysis
        message:
          $ref: '#/components/messages/PerformanceAnalysis'
  PerformanceAnalysis/Updated:
      description: ''
      publish:
        summary: PerformanceAnalysis
        message:
          $ref: '#/components/messages/PerformanceAnalysis'
components:
  messages:
    ProductPortfolioAnalysis:
        name: ProductPortfolioAnalysis
        description: >-
          Analyze the performance or behavior of some on-going activity or
          entity  within Product Portfolio. 

          Examples:- Provide behavioral insights and analysis into customer
          behavior and analyze financial market activity in order to identify
          opportunities, define pricing and evaluate risks.


          Analyze the performance or behavior of some on-going activity or
          entity. Examples:- Provide behavioral insights and analysis into
          customer behavior and analyze financial market activity in order to
          identify opportunities, define pricing and evaluate risks.
        payload:
          $ref: '#/components/schemas/ProductPortfolioAnalysis'
    PerformanceAnalysis:
        name: PerformanceAnalysis
        description: >-
          A collection of models/calculations/algoritms that can be applied to a
          subject or activity


          Examples:- Average balance calculation, Propensity to buy
        payload:
          $ref: '#/components/schemas/PerformanceAnalysis'
  schemas:
    PerformanceAnalysis:
        type: object
        description: ''
        properties:
          ProductPerformanceAnalysisType:
              type: string
              format: String
              description: "Defines the type of analysis/algorithm used to evaluate and compare the product performance to prevailing market measures \r\n"
          ProductPerformanceAnalysisTask:
              type: string
              format: String
              description: "Record of a task to perform a selected type of performance analysis on a product within the portfolio \r\n"
          ProductPerformanceRequestSpecification:
              type: string
              format: String
              description: "The specific details of the performance analysis (can be a default/standard scheduled analysis or a specialist/ad-hoc request) \r\n"
          ProductPerformanceModelReference:
              type: string
              format: Object
              description: "Reference to the performance analysis model used \r\n"
          ProductPerformanceProductandServiceActivityReport:
              type: string
              format: String
              description: "The data file, report of product related transaction details used in the analysis \r\n"
          ProductPerformanceFinancialMarketResearchReport:
              type: string
              format: String
              description: "The content of selected financial market research report or market transaction database in any suitable form used for comparisons when appropriate \r\n"
          ProductPerformanceWorkProducts:
              type: string
              format: String
              description: "Work documentation, forms and schedules produced and referenced during the analysis \r\n"
          ProductPerformanceRequestResult:
              type: string
              format: String
              description: "The output from executing the selected product performance analysis \r\n"
    ProductPortfolioAnalysis:
        type: object
        description: ''
        properties:
          ProductPortfolioMake-up:
              type: string
              format: String
              description: "Definition of the product portfolio \r\n"
          ProductType:
              type: string
              format: String
              description: "The product type within the portfolio analysis \r\n"
          ProductTypeDefinition:
              type: string
              format: String
              description: "Specific properties and characteristics of the product that provide context for the performance analysis \r\n"
          ProductPortfolioPerformanceGoals:
              type: string
              format: String
              description: "Definition of the performance goals for products as defined by senior management functions (target/anticipated and actual as assessed). \r\n"
          ProductPortfolioAnalysisSchedule:
              type: string
              format: String
              description: "The schedule for performing product portfolio analysis for the enterprise or division \r\n"
          ProductPortfolioAnalysisReport:
              type: string
              format: String
              description: "A consolidated report containing the results of performance analyses applied to the products making up the overall portfolio \r\n"
          ProductAnalysisType:
              type: string
              format: String
              description: "Defines a type of performance analysis performed to products in the portfolio (e.g. scheduled review, specialized analysis, sensitivity assessment/projection) \r\n"
          ProductAnalysisResult:
              type: string
              format: String
              description: "The consolidated report of the performance evaluation and comparisons from the analysis \r\n"
          ProductAnalysisReportingDate:
              $ref: '#/components/schemas/Date'
          DocumentDirectoryEntryInstanceReference:
              type: string
              format: Object
              description: "Reference to associated performance analysis reporting documents \r\n"
    Date:
        type: object
        format: Date
        description: >-
          The date/time the performance report was completed ISODateISODate
          (https://www.iso20022.org/standardsrepository/type/ISODate)StandardISO20022
          BM ()
        properties:
          DateContent:
              type: string
              format: String
              description: ''
