asyncapi: 2.6.0
info:
  title: Product Broker Agreement
  description: >-
    BIAN Service Domain (expanded with the BIAN BOM) | This Service domain
    maintains product broker contractual and service level agreements and tracks
    and confirms compliance and service related activity/volume goals when
    necessary
  version: 12.0.3
channels:
  BrokerAgreement/Created:
      description: ''
      publish:
        operationId: BrokerAgreement-created
        summary: BrokerAgreement
        message:
          $ref: '#/components/messages/BrokerAgreement'
  BrokerAgreement/Updated:
      description: ''
      publish:
        operationId: BrokerAgreement-updated
        summary: BrokerAgreement
        message:
          $ref: '#/components/messages/BrokerAgreement'
  LegalTerms/Created:
      description: ''
      publish:
        summary: LegalTerms
        message:
          $ref: '#/components/messages/LegalTerms'
  LegalTerms/Updated:
      description: ''
      publish:
        summary: LegalTerms
        message:
          $ref: '#/components/messages/LegalTerms'
  PolicyTerms/Created:
      description: ''
      publish:
        summary: PolicyTerms
        message:
          $ref: '#/components/messages/PolicyTerms'
  PolicyTerms/Updated:
      description: ''
      publish:
        summary: PolicyTerms
        message:
          $ref: '#/components/messages/PolicyTerms'
  RegulatoryTerms/Created:
      description: ''
      publish:
        summary: RegulatoryTerms
        message:
          $ref: '#/components/messages/RegulatoryTerms'
  RegulatoryTerms/Updated:
      description: ''
      publish:
        summary: RegulatoryTerms
        message:
          $ref: '#/components/messages/RegulatoryTerms'
components:
  messages:
    BrokerAgreement:
        name: BrokerAgreement
        description: >+
          Maintain the terms and conditions that apply to a commercial
          relationship within Product Broker Agreement.


        payload:
          $ref: '#/components/schemas/BrokerAgreement'
    LegalTerms:
        name: LegalTerms
        description: >-
          A collection of terms (within some jurisdiction) that can be selected
          and configured to define a contract /agreement


          Examples:- Required disclosures
        payload:
          $ref: '#/components/schemas/LegalTerms'
    PolicyTerms:
        name: PolicyTerms
        description: >-
          A collection of terms (within some jurisdiction) that can be selected
          and configured to define a contract /agreement


          Examples:- Required disclosures
        payload:
          $ref: '#/components/schemas/PolicyTerms'
    RegulatoryTerms:
        name: RegulatoryTerms
        description: >-
          A collection of terms (within some jurisdiction) that can be selected
          and configured to define a contract /agreement


          Examples:- Required disclosures
        payload:
          $ref: '#/components/schemas/RegulatoryTerms'
  schemas:
    LegalTerms:
        type: object
        description: ''
        properties:
          Jurisdiction:
              type: string
              format: String
              description: "The legal jurisdiction \r\n"
          ApplicableLawReference:
              type: string
              format: Object
              description: "Reference to any legal requirements \r\n"
          ApplicableLawInterpretation:
              type: string
              format: String
              description: "Explanation or interpretation of the law as applied \r\n"
    PolicyTerms:
        type: object
        description: ''
        properties:
          BankPolicy-RuleType:
              type: string
              format: String
              description: "The type of bank policy referenced (e.g. staff certification) \r\n"
          ApplicableBankPolicy-RuleReference:
              type: string
              format: Object
              description: "Reference to the bank's policies or rules \r\n"
          ApplicableBankPolicy-RuleInterpretation:
              type: string
              format: String
              description: "Explanation or interpretation of the policy or rule as applied \r\n"
    RegulatoryTerms:
        type: object
        description: ''
        properties:
          RegulatoryAuthority:
              type: string
              format: String
              description: "The applicable regulatory authority \r\n"
          ApplicableRegulationReference:
              type: string
              format: Object
              description: "Reference to any regulatory requirements \r\n"
          ApplicableRegulationInterpretation:
              type: string
              format: String
              description: "Explanation or interpretation of the regulation as applied \r\n"
    BrokerAgreement:
        type: object
        description: ''
        properties:
          PartyReference:
              type: string
              format: Object
              description: "Reference to the broker organization \r\n"
          AgreementType:
              type: string
              format: String
              description: "The type of agreement (e.g. service provider, product alliance) \r\n"
          AgreementJurisdiction:
              type: string
              format: String
              description: "The contractual jurisdiction or coverage of the agreement (e.g. \"governed by State\") \r\n"
          AgreementValidFromToDate:
              $ref: '#/components/schemas/Date'
          AgreementSignaturesResponsibleParties:
              type: string
              format: String
              description: "Reference to signatories \r\n"
          DocumentDirectoryEntryInstanceReference:
              type: string
              format: Object
              description: "Reference to any associated documents \r\n"
    Date:
        type: object
        format: Date
        description: >-
          The term of the agreement ISODateISODate
          (https://www.iso20022.org/standardsrepository/type/ISODate)StandardISO20022
          BM ()
        properties:
          DateContent:
              type: string
              format: String
              description: ''
