asyncapi: 2.6.0
info:
  title: Product Combination
  description: >-
    BIAN Service Domain (expanded with the BIAN BOM) | Product Combination
    supports bundled products applying necessary constraints on embedded product
    fulfillment and ensuring product performance analysis takes correct account
    of embedded products' contribution
  version: 12.0.3
channels:
  ProductCombinationFacility/Created:
      description: ''
      publish:
        operationId: ProductCombinationFacility-created
        summary: ProductCombinationFacility
        message:
          $ref: '#/components/messages/ProductCombinationFacility'
  ProductCombinationFacility/Updated:
      description: ''
      publish:
        operationId: ProductCombinationFacility-updated
        summary: ProductCombinationFacility
        message:
          $ref: '#/components/messages/ProductCombinationFacility'
  EmbeddedProductControl/Created:
      description: ''
      publish:
        summary: EmbeddedProductControl
        message:
          $ref: '#/components/messages/EmbeddedProductControl'
  EmbeddedProductControl/Updated:
      description: ''
      publish:
        summary: EmbeddedProductControl
        message:
          $ref: '#/components/messages/EmbeddedProductControl'
  ProductCombinationOutcome/Created:
      description: ''
      publish:
        summary: ProductCombinationOutcome
        message:
          $ref: '#/components/messages/ProductCombinationOutcome'
  ProductCombinationOutcome/Updated:
      description: ''
      publish:
        summary: ProductCombinationOutcome
        message:
          $ref: '#/components/messages/ProductCombinationOutcome'
  Fulfillment/Created:
      description: ''
      publish:
        summary: Fulfillment
        message:
          $ref: '#/components/messages/Fulfillment'
  Fulfillment/Updated:
      description: ''
      publish:
        summary: Fulfillment
        message:
          $ref: '#/components/messages/Fulfillment'
  TransferPricing/Created:
      description: ''
      publish:
        summary: TransferPricing
        message:
          $ref: '#/components/messages/TransferPricing'
  TransferPricing/Updated:
      description: ''
      publish:
        summary: TransferPricing
        message:
          $ref: '#/components/messages/TransferPricing'
components:
  messages:
    ProductCombinationFacility:
        name: ProductCombinationFacility
        description: >-
          Fulfill any scheduled and ad-hoc obligations under a service
          arrangement, most typically for a financial product or facility 
          within Product Combination. 

          Example: Perform the scheduled (e.g. statements, standing orders) and
          ad-hoc/requested (e.g. balance inquiries, fund transfers) fulfillment
          tasks for a customer current account facility.
        payload:
          $ref: '#/components/schemas/ProductCombinationFacility'
    EmbeddedProductControl:
        name: EmbeddedProductControl
        description: >-
          Fulfill any scheduled and ad-hoc obligations under a service
          arrangement, most typically for a financial product or facility 
          within Product Combination. 

          Example: Perform the scheduled (e.g. statements, standing orders) and
          ad-hoc/requested (e.g. balance inquiries, fund transfers) fulfillment
          tasks for a customer current account facility.
        payload:
          $ref: '#/components/schemas/EmbeddedProductControl'
    ProductCombinationOutcome:
        name: ProductCombinationOutcome
        description: >-
          Fulfill any scheduled and ad-hoc obligations under a service
          arrangement, most typically for a financial product or facility 
          within Product Combination. 

          Example: Perform the scheduled (e.g. statements, standing orders) and
          ad-hoc/requested (e.g. balance inquiries, fund transfers) fulfillment
          tasks for a customer current account facility.
        payload:
          $ref: '#/components/schemas/ProductCombinationOutcome'
    Fulfillment:
        name: Fulfillment
        description: >-
          Fulfill any scheduled and ad-hoc obligations under a service
          arrangement, most typically for a financial product or facility 
          within Product Combination. 

          Example: Perform the scheduled (e.g. statements, standing orders) and
          ad-hoc/requested (e.g. balance inquiries, fund transfers) fulfillment
          tasks for a customer current account facility.
        payload:
          $ref: '#/components/schemas/Fulfillment'
    TransferPricing:
        name: TransferPricing
        description: >-
          Fulfill any scheduled and ad-hoc obligations under a service
          arrangement, most typically for a financial product or facility 
          within Product Combination. 

          Example: Perform the scheduled (e.g. statements, standing orders) and
          ad-hoc/requested (e.g. balance inquiries, fund transfers) fulfillment
          tasks for a customer current account facility.
        payload:
          $ref: '#/components/schemas/TransferPricing'
  schemas:
    EmbeddedProductControl:
        type: object
        description: ''
        properties:
          EmbeddedProductControlPreconditions:
              type: string
              format: String
              description: "The required status/situation prior to the implementation of the feature \r\n"
          EmbeddedProductControlFeatureSchedule:
              type: string
              format: String
              description: "The timing and key actions/milestones involved in completing the fulfillment feature instance \r\n"
          CombinedProductControl:
              $ref: '#/components/schemas/BusinessService'
          EmbeddedProductControlPostconditions:
              type: string
              format: String
              description: "The completion status and any triggered/dependent actions once the feature instance has been fulfilled \r\n"
          EmbeddedProductControlCombinedProductControlServiceType:
              type: string
              format: String
              description: "Reference to the specific business service type \r\n"
          EmbeddedProductControlCombinedProductControlServiceDescription:
              type: string
              format: String
              description: "Description of the performed business service \r\n"
          EmbeddedProductControlCombinedProductControlServiceInputsandOuputs:
              type: string
              format: String
              description: "Mandatory and optional inputs and output information for the business service \r\n"
          EmbeddedProductControlCombinedProductControlServiceWorkProduct:
              type: string
              format: String
              description: "Documentation, meeting schedules, notes, reasearch. calculations and any other work products produced by the business service \r\n"
          EmbeddedProductControlCombinedProductControlServiceName:
              type: string
              format: String
              description: ''
    BusinessService:
        type: object
        format: BusinessService
        description: "The Product Combination Arrangement specific Business Service \r\n"
        properties:
          BusinessServiceType:
              enum:
                  -  Businessservicetypevalues
              format: BusinessService
    ProductCombinationOutcome:
        type: object
        description: ''
        properties:
          ProductCombinationFinancialFacility:
              type: string
              format: String
              description: ''
          ProductCombinationWorkProduct:
              type: string
              format: String
              description: ''
    Fulfillment:
        type: object
        description: ''
        properties:
          FulfillmentPreconditions:
              type: string
              format: String
              description: "The required status/situation prior to the implementation of the feature \r\n"
          FulfillmentFeatureSchedule:
              type: string
              format: String
              description: "The timing and key actions/milestones involved in completing the fulfillment feature instance \r\n"
          FiduciaryArrangementFulfillment:
              $ref: '#/components/schemas/BusinessService'
          FulfillmentPostconditions:
              type: string
              format: String
              description: "The completion status and any triggered/dependent actions once the feature instance has been fulfilled \r\n"
          FulfillmentFiduciaryArrangementFulfillmentServiceType:
              type: string
              format: String
              description: "Reference to the specific business service type \r\n"
          FulfillmentFiduciaryArrangementFulfillmentServiceDescription:
              type: string
              format: String
              description: "Description of the performed business service \r\n"
          FulfillmentFiduciaryArrangementFulfillmentServiceInputsandOuputs:
              type: string
              format: String
              description: "Mandatory and optional inputs and output information for the business service \r\n"
          FulfillmentFiduciaryArrangementFulfillmentServiceWorkProduct:
              type: string
              format: String
              description: "Documentation, meeting schedules, notes, reasearch. calculations and any other work products produced by the business service \r\n"
          FulfillmentFiduciaryArrangementFulfillmentServiceName:
              type: string
              format: String
              description: ''
    TransferPricing:
        type: object
        description: ''
        properties:
          TransferPricingPreconditions:
              type: string
              format: String
              description: "The required status/situation prior to the implementation of the feature \r\n"
          TransferPricingFeatureSchedule:
              type: string
              format: String
              description: "The timing and key actions/milestones involved in completing the fulfillment feature instance \r\n"
          ProductTransferPricing:
              $ref: '#/components/schemas/BusinessService'
          TransferPricingPostconditions:
              type: string
              format: String
              description: "The completion status and any triggered/dependent actions once the feature instance has been fulfilled \r\n"
          TransferPricingProductTransferPricingServiceType:
              type: string
              format: String
              description: "Reference to the specific business service type \r\n"
          TransferPricingProductTransferPricingServiceDescription:
              type: string
              format: String
              description: "Description of the performed business service \r\n"
          TransferPricingProductTransferPricingServiceInputsandOuputs:
              type: string
              format: String
              description: "Mandatory and optional inputs and output information for the business service \r\n"
          TransferPricingProductTransferPricingServiceWorkProduct:
              type: string
              format: String
              description: "Documentation, meeting schedules, notes, reasearch. calculations and any other work products produced by the business service \r\n"
          TransferPricingProductTransferPricingServiceName:
              type: string
              format: String
              description: ''
    ProductCombinationFacility:
        type: object
        description: ''
        properties:
          ProductCombinationFacilityParameterType:
              type: string
              format: String
              description: "A Classification value that distinguishes between arrangements according to the type of business services within Product Combination Arrangement \r\n"
          ProductCombinationFacilitySelectedOption:
              type: string
              format: String
              description: "A selected optional business service as subject matter of Product Combination Arrangement \r\n"
          ProductCombinationFacilityType:
              type: string
              format: String
              description: "The type of Product Combination Arrangement \r\n"
          ProductCombinationFacilityReference:
              type: string
              format: Object
              description: "Reference to Product Combination Arrangement \r\n"
          ProductCombinationFacilitySchedule:
              type: string
              format: String
              description: "Timetable to fulfill Product Combination Arrangement \r\n"
          ProductCombinationFacilityStatus:
              type: string
              format: String
              description: "The status of Product Combination Arrangement \r\n"
          ProductCombinationFacilityCurrency:
              $ref: '#/components/schemas/Currencycode'
          ProductCombinationFacilityRegulationReference:
              type: string
              format: Object
              description: "Reference to the regulation which is defined in Product Combination Arrangement \r\n"
          ProductCombinationFacilityRegulationType:
              type: string
              format: String
              description: "A Classification that distinguishes between the regularity domains of Product Combination Arrangement \r\n"
          ProductCombinationFacilityJurisdiction:
              type: string
              format: String
              description: "Reference to the jurisdiction that is assigned to Product Combination Arrangement in case of legal dispute. \r\n"
          ProductCombinationFacilityBookingLocation:
              type: string
              format: String
              description: "The financial accounting unit into which the financial events, with regard to the origination and fulfillment of the agreement in the context of Product Combination Arrangement, are entered. \r\n"
          ProductCombinationFacilityAccountType:
              type: string
              format: String
              description: "The type of account which is linked to Product Combination Arrangement \r\n"
          ProductCombinationFacilityAccountReference:
              type: string
              format: Object
              description: "Reference to the account which is linked to Product Combination Arrangement \r\n"
    Currencycode:
        type: object
        format: Currencycode
        description: >-
          The curreny which is arranged in Product Combination Arrangement
          CurrencyCodeCurrencyCode
          (https://www.iso20022.org/standardsrepository/type/CurrencyCode)StandardISO20022
          BM ()
        properties:
          Currencycode:
              type: string
              format: DataType
              description: >-
                A code identifying a currency according to ISO-4217.

                A currency is a system of money in general use in a particular
                country.


                Code allocated to a currency, by a maintenance agency, under an
                international identification scheme as described in the latest
                edition of the international standard ISO 4217 "Codes for the
                representation of currencies and funds". Valid currency codes
                are registered with the ISO 4217 Maintenance Agency, and consist
                of three contiguous letters. (ISO20022)

                 
