asyncapi: 2.6.0
info:
  title: Production Release
  description: >-
    BIAN Service Domain (expanded with the BIAN BOM) | Maintain and apply
    production release tests for new and updated systems
  version: 12.0.3
channels:
  ProductionSystemAssessment/Created:
      description: ''
      publish:
        operationId: ProductionSystemAssessment-created
        summary: ProductionSystemAssessment
        message:
          $ref: '#/components/messages/ProductionSystemAssessment'
  ProductionSystemAssessment/Updated:
      description: ''
      publish:
        operationId: ProductionSystemAssessment-updated
        summary: ProductionSystemAssessment
        message:
          $ref: '#/components/messages/ProductionSystemAssessment'
  OperationalRisk/Created:
      description: ''
      publish:
        summary: OperationalRisk
        message:
          $ref: '#/components/messages/OperationalRisk'
  OperationalRisk/Updated:
      description: ''
      publish:
        summary: OperationalRisk
        message:
          $ref: '#/components/messages/OperationalRisk'
  BusinessRisk/Created:
      description: ''
      publish:
        summary: BusinessRisk
        message:
          $ref: '#/components/messages/BusinessRisk'
  BusinessRisk/Updated:
      description: ''
      publish:
        summary: BusinessRisk
        message:
          $ref: '#/components/messages/BusinessRisk'
  ProductionRisk/Created:
      description: ''
      publish:
        summary: ProductionRisk
        message:
          $ref: '#/components/messages/ProductionRisk'
  ProductionRisk/Updated:
      description: ''
      publish:
        summary: ProductionRisk
        message:
          $ref: '#/components/messages/ProductionRisk'
  FunctionalRisk/Created:
      description: ''
      publish:
        summary: FunctionalRisk
        message:
          $ref: '#/components/messages/FunctionalRisk'
  FunctionalRisk/Updated:
      description: ''
      publish:
        summary: FunctionalRisk
        message:
          $ref: '#/components/messages/FunctionalRisk'
components:
  messages:
    ProductionSystemAssessment:
        name: ProductionSystemAssessment
        description: >-
          To test or assess an entity, possibly against some formal
          qualification or certification requirement within Production Release. 
        payload:
          $ref: '#/components/schemas/ProductionSystemAssessment'
    OperationalRisk:
        name: OperationalRisk
        description: 
          All kind of verifications 

          Examples:- Password verification
        payload:
          $ref: '#/components/schemas/OperationalRisk'
    BusinessRisk:
        name: BusinessRisk
        description: 
          All kind of verifications 

          Examples:- Password verification
        payload:
          $ref: '#/components/schemas/BusinessRisk'
    ProductionRisk:
        name: ProductionRisk
        description: 
          All kind of verifications 

          Examples:- Password verification
        payload:
          $ref: '#/components/schemas/ProductionRisk'
    FunctionalRisk:
        name: FunctionalRisk
        description: 
          All kind of verifications 

          Examples:- Password verification
        payload:
          $ref: '#/components/schemas/FunctionalRisk'
  schemas:
    OperationalRisk:
        type: object
        description: ''
        properties:
          OperationalRiskSystemTestType:
              type: string
              format: String
              description: "The type of operational risk test being performed (e.g. operator error recovery, major IT component failure recovery/continuity) \r\n"
          OperationalRiskSystemTestDescription:
              type: string
              format: String
              description: "Detailed description of the test, including expected results \r\n"
          OperationalRiskSystemTestWorkProduct:
              type: string
              format: String
              description: "Reference to testing materials, results, assessments and other documents \r\n"
          OperationalRiskSystemTestResult:
              type: string
              format: String
              description: "The result of the operational risk test (including required remedial actions/fixes where appropriate) \r\n"
    BusinessRisk:
        type: object
        description: ''
        properties:
          BusinessRiskSystemTestType:
              type: string
              format: String
              description: "The type of business risk test being performed (e.g. compliance, pricing, exposure) \r\n"
          BusinessRiskSystemTestDescription:
              type: string
              format: String
              description: "Detailed description of the test, including expected results \r\n"
          BusinessRiskTestWorkProduct:
              type: string
              format: String
              description: "Reference to testing materials, results, assessments and other documents \r\n"
          BusinessRiskTestResult:
              type: string
              format: String
              description: "The result of the business risk test (including required remedial actions/fixes where appropriate) \r\n"
    ProductionRisk:
        type: object
        description: ''
        properties:
          ProductionRiskSystemTestType:
              type: string
              format: String
              description: "The type of production test being performed (e.g. division of responsibilities, access control, audit trail, back-up and recovery) \r\n"
          ProductionRiskSystemTestDescription:
              type: string
              format: String
              description: "Detailed description of the test, including expected results \r\n"
          ProductionRiskSystemTestWorkProduct:
              type: string
              format: String
              description: "Reference to testing materials, results, assessments and other documents \r\n"
          ProductionRiskSystemTestResult:
              type: string
              format: String
              description: "The result of the production risk test (including required remedial actions/fixes where appropriate) \r\n"
    FunctionalRisk:
        type: object
        description: ''
        properties:
          FunctionalRiskSystemTestType:
              type: string
              format: String
              description: "The type of functional test being performed (e.g. functional coverage/integrity, usability, application integration) \r\n"
          FunctionalRiskSystemTestDescription:
              type: string
              format: String
              description: "Detailed description of the test, including expected results \r\n"
          FunctionalRiskSystemTestWorkProduct:
              type: string
              format: String
              description: "Reference to testing materials, results, assessments and other documents \r\n"
          FunctionalRiskSystemTestResult:
              type: string
              format: String
              description: "The result of the functional risk test (including required remedial actions/fixes where appropriate) \r\n"
    ProductionSystemAssessment:
        type: object
        description: ''
        properties:
          ProductionReleaseName:
              type: string
              format: String
              description: "The reference to and descriptive name of the production release system \r\n"
          EmployeeBusinessUnitReference:
              type: string
              format: Object
              description: "Reference to the business units responsible for the testing and deployment \r\n"
          ProductionReleaseType:
              type: string
              format: String
              description: "The type of production release (e.g. production service update, new production system) \r\n"
          ProductionReleaseDescription:
              type: string
              format: String
              description: "A description of the scope, goal and make-up of the production release \r\n"
          ProductionReleaseTestProfile:
              type: string
              format: String
              description: "Details the types of production release tests to be and actually applied \r\n"
          ProductionReleaseTestSchedule:
              type: string
              format: String
              description: "The schedule for performing the range of release tests (planned and actual) \r\n"
          ProductionReleaseConsolidationRecord:
              type: string
              format: String
              description: "The consolidated release evaluation combining the results of all underlying tests \r\n"
          DocumentDirectoryEntryInstanceReference:
              type: string
              format: Object
              description: "Reference to associated documents \r\n"
          DateType:
              type: string
              format: String
              description: "Key dates associated with the assessment (e.g. notification date, commencement  date, completion date) \r\n"
          Date:
              type: string
              format: String
              description: "Value of the specific date type \r\n"
