asyncapi: 2.6.0
info:
  title: Product Training
  description: >-
    BIAN Service Domain (expanded with the BIAN BOM) | Develop and provide
    product specific training across the workforce. This includes all media and
    training mechanisms (on-line, self taught, classroom etc.)
  version: 12.0.3
channels:
  ProductTrainingProcedure/Created:
      description: ''
      publish:
        operationId: ProductTrainingProcedure-created
        summary: ProductTrainingProcedure
        message:
          $ref: '#/components/messages/ProductTrainingProcedure'
  ProductTrainingProcedure/Updated:
      description: ''
      publish:
        operationId: ProductTrainingProcedure-updated
        summary: ProductTrainingProcedure
        message:
          $ref: '#/components/messages/ProductTrainingProcedure'
  ProductTrainingOutcome/Created:
      description: ''
      publish:
        summary: ProductTrainingOutcome
        message:
          $ref: '#/components/messages/ProductTrainingOutcome'
  ProductTrainingOutcome/Updated:
      description: ''
      publish:
        summary: ProductTrainingOutcome
        message:
          $ref: '#/components/messages/ProductTrainingOutcome'
  ServiceScheduling/Created:
      description: ''
      publish:
        summary: ServiceScheduling
        message:
          $ref: '#/components/messages/ServiceScheduling'
  ServiceScheduling/Updated:
      description: ''
      publish:
        summary: ServiceScheduling
        message:
          $ref: '#/components/messages/ServiceScheduling'
  ServiceEvaluation/Created:
      description: ''
      publish:
        summary: ServiceEvaluation
        message:
          $ref: '#/components/messages/ServiceEvaluation'
  ServiceEvaluation/Updated:
      description: ''
      publish:
        summary: ServiceEvaluation
        message:
          $ref: '#/components/messages/ServiceEvaluation'
  ServiceDelivery/Created:
      description: ''
      publish:
        summary: ServiceDelivery
        message:
          $ref: '#/components/messages/ServiceDelivery'
  ServiceDelivery/Updated:
      description: ''
      publish:
        summary: ServiceDelivery
        message:
          $ref: '#/components/messages/ServiceDelivery'
  ContentDevelopment/Created:
      description: ''
      publish:
        summary: ContentDevelopment
        message:
          $ref: '#/components/messages/ContentDevelopment'
  ContentDevelopment/Updated:
      description: ''
      publish:
        summary: ContentDevelopment
        message:
          $ref: '#/components/messages/ContentDevelopment'
components:
  messages:
    ProductTrainingProcedure:
        name: ProductTrainingProcedure
        description: >-
          Complete work tasks following a defined procedure in support of
          general office activities and product and service delivery  within
          Product Training. 

          Example: Process the evaluation and completion of customer offers.
        payload:
          $ref: '#/components/schemas/ProductTrainingProcedure'
    ProductTrainingOutcome:
        name: ProductTrainingOutcome
        description: 
          The main worsteps to be followed in th eexecution of the procedure

          Examples:- Invoice generation
        payload:
          $ref: '#/components/schemas/ProductTrainingOutcome'
    ServiceScheduling:
        name: ServiceScheduling
        description: 
          The main worsteps to be followed in th eexecution of the procedure

          Examples:- Invoice generation
        payload:
          $ref: '#/components/schemas/ServiceScheduling'
    ServiceEvaluation:
        name: ServiceEvaluation
        description: 
          The main worsteps to be followed in th eexecution of the procedure

          Examples:- Invoice generation
        payload:
          $ref: '#/components/schemas/ServiceEvaluation'
    ServiceDelivery:
        name: ServiceDelivery
        description: 
          The main worsteps to be followed in th eexecution of the procedure

          Examples:- Invoice generation
        payload:
          $ref: '#/components/schemas/ServiceDelivery'
    ContentDevelopment:
        name: ContentDevelopment
        description: 
          The main worsteps to be followed in th eexecution of the procedure

          Examples:- Invoice generation
        payload:
          $ref: '#/components/schemas/ContentDevelopment'
  schemas:
    ProductTrainingOutcome:
        type: object
        description: ''
        properties:
          ProductTrainingWorkProduct:
              type: string
              format: String
              description: ''
          ProductTrainingProcedure:
              type: string
              format: String
              description: ''
    ServiceScheduling:
        type: object
        description: ''
        properties:
          ServiceSchedulingPreconditions:
              type: string
              format: String
              description: "The required status/situation and or tasks that need to be completed prior to the initiation of the workstep \r\n"
          ServiceSchedulingBusinessUnitEmployeeReference:
              type: string
              format: Object
              description: "The operating unit/employee responsible for the workstep \r\n"
          ServiceSchedulingWorkSchedule:
              type: string
              format: String
              description: "The timing and key actions/milestones making up the workstep \r\n"
          ServiceScheduling:
              $ref: '#/components/schemas/BusinessService'
          ServiceSchedulingPostconditions:
              type: string
              format: String
              description: "The completion status and reference to subsequent actions that may be triggered on completion of the workstep \r\n"
          ServiceSchedulingServiceSchedulingServiceType:
              type: string
              format: String
              description: "Reference to the specific business service type \r\n"
          ServiceSchedulingServiceSchedulingServiceDescription:
              type: string
              format: String
              description: "Description of the performed business service \r\n"
          ServiceSchedulingServiceSchedulingServiceInputsandOuputs:
              type: string
              format: String
              description: "Mandatory and optional inputs and output information for the business service \r\n"
          ServiceSchedulingServiceSchedulingServiceWorkProduct:
              type: string
              format: String
              description: "Documentation, meeting schedules, notes, reasearch. calculations and any other work products produced by the business service \r\n"
          ServiceSchedulingServiceSchedulingServiceName:
              type: string
              format: String
              description: ''
    BusinessService:
        type: object
        format: BusinessService
        description: "The Product Training Procedure specific Business Service \r\n"
        properties:
          BusinessServiceType:
              enum:
                  -  Businessservicetypevalues
              format: BusinessService
    ServiceEvaluation:
        type: object
        description: ''
        properties:
          ServiceEvaluationPreconditions:
              type: string
              format: String
              description: "The required status/situation and or tasks that need to be completed prior to the initiation of the workstep \r\n"
          ServiceEvaluationBusinessUnitEmployeeReference:
              type: string
              format: Object
              description: "The operating unit/employee responsible for the workstep \r\n"
          ServiceEvaluationWorkSchedule:
              type: string
              format: String
              description: "The timing and key actions/milestones making up the workstep \r\n"
          ServiceEvaluation:
              $ref: '#/components/schemas/BusinessService'
          ServiceEvaluationPostconditions:
              type: string
              format: String
              description: "The completion status and reference to subsequent actions that may be triggered on completion of the workstep \r\n"
          ServiceEvaluationServiceEvaluationServiceType:
              type: string
              format: String
              description: "Reference to the specific business service type \r\n"
          ServiceEvaluationServiceEvaluationServiceDescription:
              type: string
              format: String
              description: "Description of the performed business service \r\n"
          ServiceEvaluationServiceEvaluationServiceInputsandOuputs:
              type: string
              format: String
              description: "Mandatory and optional inputs and output information for the business service \r\n"
          ServiceEvaluationServiceEvaluationServiceWorkProduct:
              type: string
              format: String
              description: "Documentation, meeting schedules, notes, reasearch. calculations and any other work products produced by the business service \r\n"
          ServiceEvaluationServiceEvaluationServiceName:
              type: string
              format: String
              description: ''
    ServiceDelivery:
        type: object
        description: ''
        properties:
          ServiceDeliveryPreconditions:
              type: string
              format: String
              description: "The required status/situation and or tasks that need to be completed prior to the initiation of the workstep \r\n"
          ServiceDeliveryBusinessUnitEmployeeReference:
              type: string
              format: Object
              description: "The operating unit/employee responsible for the workstep \r\n"
          ServiceDeliveryWorkSchedule:
              type: string
              format: String
              description: "The timing and key actions/milestones making up the workstep \r\n"
          ServiceDelivery:
              $ref: '#/components/schemas/BusinessService'
          ServiceDeliveryPostconditions:
              type: string
              format: String
              description: "The completion status and reference to subsequent actions that may be triggered on completion of the workstep \r\n"
          ServiceDeliveryServiceDeliveryServiceType:
              type: string
              format: String
              description: "Reference to the specific business service type \r\n"
          ServiceDeliveryServiceDeliveryServiceDescription:
              type: string
              format: String
              description: "Description of the performed business service \r\n"
          ServiceDeliveryServiceDeliveryServiceInputsandOuputs:
              type: string
              format: String
              description: "Mandatory and optional inputs and output information for the business service \r\n"
          ServiceDeliveryServiceDeliveryServiceWorkProduct:
              type: string
              format: String
              description: "Documentation, meeting schedules, notes, reasearch. calculations and any other work products produced by the business service \r\n"
          ServiceDeliveryServiceDeliveryServiceName:
              type: string
              format: String
              description: ''
    ContentDevelopment:
        type: object
        description: ''
        properties:
          ContentDevelopmentPreconditions:
              type: string
              format: String
              description: "The required status/situation and or tasks that need to be completed prior to the initiation of the workstep \r\n"
          ContentDevelopmentBusinessUnitEmployeeReference:
              type: string
              format: Object
              description: "The operating unit/employee responsible for the workstep \r\n"
          ContentDevelopmentWorkSchedule:
              type: string
              format: String
              description: "The timing and key actions/milestones making up the workstep \r\n"
          ContentDevelopment:
              $ref: '#/components/schemas/BusinessService'
          ContentDevelopmentPostconditions:
              type: string
              format: String
              description: "The completion status and reference to subsequent actions that may be triggered on completion of the workstep \r\n"
          ContentDevelopmentContentDevelopmentServiceType:
              type: string
              format: String
              description: "Reference to the specific business service type \r\n"
          ContentDevelopmentContentDevelopmentServiceDescription:
              type: string
              format: String
              description: "Description of the performed business service \r\n"
          ContentDevelopmentContentDevelopmentServiceInputsandOuputs:
              type: string
              format: String
              description: "Mandatory and optional inputs and output information for the business service \r\n"
          ContentDevelopmentContentDevelopmentServiceWorkProduct:
              type: string
              format: String
              description: "Documentation, meeting schedules, notes, reasearch. calculations and any other work products produced by the business service \r\n"
          ContentDevelopmentContentDevelopmentServiceName:
              type: string
              format: String
              description: ''
    ProductTrainingProcedure:
        type: object
        description: ''
        properties:
          ProductTrainingProcedureParameterType:
              type: string
              format: String
              description: "A Classification value that distinguishes between Procedures according to the type of business services and/or type of concern defined within Product Training Procedure \r\n"
          ProductTrainingProcedureSelectedOption:
              type: string
              format: String
              description: "A selected optional business service as subject matter of Product Training Procedure \r\n"
          ProductTrainingProcedureRequest:
              type: string
              format: String
              description: "Request to process ProductTraining \r\n"
          ProductTrainingProcedureSchedule:
              type: string
              format: String
              description: "Timetable to process ProductTraining \r\n"
          ProductTrainingProcedureStatus:
              type: string
              format: String
              description: "The status of Product Training Procedure \r\n"
          ProductTrainingProcedureReference:
              type: string
              format: Object
              description: "Reference to the party who is involved in Product Training Procedure \r\n"
          ProductTrainingProcedureBusinessUnitReference:
              type: string
              format: Object
              description: "Reference to the business unit which is involved in Product Training Procedure \r\n"
          ProductTrainingProcedureServiceProviderReference:
              type: string
              format: Object
              description: "Reference to the party who is the service provider of Product Training Procedure \r\n"
          ProductTrainingProcedureFinancialFacilityReference:
              type: string
              format: Object
              description: "Reference to the Financial Facility related to  Product Training Procedure  \r\n"
          ProductTrainingProcedureEmployeeReference:
              type: string
              format: Object
              description: "Reference to the employee who is involved in Product Training Procedure \r\n"
          ProductTrainingProcedureCustomerReference:
              type: string
              format: Object
              description: "Reference to the customer who is involved in Product Training Procedure \r\n"
          ProductTrainingProcedureType:
              type: string
              format: String
              description: "A Classification value that distinguishes between the type of process undertaken within Product Training Procedure \r\n"
          ProductTrainingProcedureServiceProviderSchedule:
              type: string
              format: String
              description: "The schedule according to which the service provider will process the Product Training Procedure \r\n"
          ProductTrainingProcedureServiceType:
              type: string
              format: String
              description: "A Classification value that distinguishes between the type of services in Product Training Procedure  \r\n"
          ProductTrainingProcedureProductandServiceType:
              type: string
              format: String
              description: "A Classification value that distinguishes between the type of products/services related to Product Training Procedure  \r\n"
          ProductTrainingProcedureProductandServiceInstance:
              type: string
              format: String
              description: "Reference to the product or service that is related to  Product Training Procedure \r\n"
          ProductTrainingProcedureTransactionType:
              type: string
              format: String
              description: "A Classification value that distinguishes between the type of transactions in Product Training Procedure  \r\n"
          ProductTrainingProcedureTransaction:
              type: string
              format: String
              description: "Reference to the transaction that is related to  Product Training Procedure  \r\n"
          ProductTrainingProcedureFinancialTransactionArrangement:
              type: string
              format: String
              description: "Reference to the Financial Transaction Arrangement that is related to  Product Training Procedure  \r\n"
          ProductTrainingProcedureCustomerAgreementReference:
              type: string
              format: Object
              description: "Reference to the Customer Agreement that is related to  Product Training Procedure  \r\n"
